### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by cmpaul**
Addresses issue #20 . 

This fixes some build and server issues when I'm running this locally, but I definitely foresee this causing issues for those whose systems are not current. Since this is a demo application, I'm assuming that's not a huge issue, but let me know if I'm off base.

Thanks!

### CODE REVIEW

**Comment by cmpaul** [comment]
^ Realizing that .travis.yml will need to be updated to reflect the dependency changes.

**Comment by doomspork** [comment]
Thank you @cmpaul!  Could you update `.travis.yml`?

**Comment by cmpaul** [comment]
@doomspork Yep, will do later today!

**Comment by cmpaul** [comment]
@doomspork All set. ✨

**Comment by doomspork** [comment]
Perfect!  Thank you @cmpaul 👍

**Pull request merged**
