### PR TITLE
remove any references to the ecto.repo as it is not used and not needed

### PR DESCRIPTION
**Pull request by wribln**
I hope this is all needed/required.

### CODE REVIEW

**Comment by wribln** [comment]
I was not aware of the importance of .formatter.exs and so I removed this file. You might want to undo this change...

**Comment by wribln** [comment]
(still learning ;-)

**Comment by yordis** [comment]
Let me know once you think you are done

**Comment by wribln** [comment]
I think I am done.

**Review by yordis — APPROVED** [review]

**Pull request merged**
