### PR TITLE
Fix ueberauth_github sample.

### PR DESCRIPTION
**Pull request by ramortegui**
This PR updates the libraries related with `ueberauth_github` issue and solves https://github.com/ueberauth/ueberauth_example/issues/23

On heroku sample app:
image

Locally I was able to reproduce it:
image

After updating libraries:
image

### CODE REVIEW

**Comment by ramortegui** [comment]
@doomspork great!.  Any chance to re-deploy the heroku app? ( to test it ;) )

**Comment by doomspork** [comment]
@ramortegui it should be autodeploying now, just give it a few minutes to get there 😁

**Comment by ramortegui** [comment]
@doomspork I checked the app on heroku, and still isn't working.  So, I deployed the master branch in heroku: https://warm-chamber-41439.herokuapp.com/ and I configure it using a custom oauth app. (see config below), and is working.

Screenshot from 2019-11-22 22-57-25

Could you check the github app? (credentials, urls, logs)

Thanks ;)

image

**Comment by ramortegui** [comment]
@doomspork any chance to look up the github app❓

**Pull request merged**
